### PR TITLE
Rework `JsonConvert` for performance and maintainability

### PR DESCRIPTION
**Pull request by CoryCharlton**
## Description
- Condense duplicate code
- Improve type checking
- General best practice refactoring (ie: use `is` for null checks)

## Motivation and Context
While I was digging through `JsonConvert` I saw a bunch of duplicate code and room for improvement. There's still a few ideas I have for further improvement but I'll hold off on those. Long story short most of the deserialization benchmarks saw a ~25% improvement.

## How Has This Been Tested?
- Unit tests
- Live device

## Types of changes

- [x] Improvement (non-breaking change that improves a feature, code or algorithm)
- [ ] Bug fix (non-breaking change which fixes an issue with code or algorithm)
- [ ] New feature (non-breaking change which adds functionality to code)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Config and build (change in the configuration and build system, has no impact on code or features)
- [ ] Dependencies (update dependencies and changes associated, has no impact on code or features)
- [x] Unit Tests (add new Unit Test(s) or improved existing one(s), has no impact on code or features)
- [ ] Documentation (changes or updates in the documentation, has no impact on code or features)

## Checklist:

- [x] My code follows the code style of this project (only if there are changes in source code).
- [ ] My changes require an update to the documentation (there are changes that require the docs website to be updated).
- [ ] I have updated the documentation accordingly (the changes require an update on the docs in this repo).
- [x] I have read the [CONTRIBUTING](https://github.com/nanoframework/.github/blob/main/CONTRIBUTING.md) document.
- [x] I have tested everything locally and all new and existing tests passed (only if there are changes in source code).
- [x] I have added new tests to cover my changes.

### CODE REVIEW

**Comment by CoryCharlton** [comment]
I still have some cleanup I need to do on this and will need to wait until I merge in https://github.com/nanoframework/nanoFramework.Json/pull/333

**Comment by Ellerbach** [comment]
Nice work making it super hard to review the PR! That said, if all the existing tests are green and the performance is increased, I'm all up a big fan :-)

**Comment by josesimoes** [comment]
Hey @CoryCharlton! I've just tumbled on this PR. 😁 Wondering if you're planning to resume these changes/improvements?

**Comment by CoryCharlton** [comment]
> Hey @CoryCharlton! I've just tumbled on this PR. 😁 Wondering if you're planning to resume these changes/improvements?

Hi @josesimoes , I ran into some issues with this where the behavior of my changes was not entirely consistent with the old code. Now that I've got some time again I'm going to break this down into smaller, more testable, chunks. I'll have a PR shortly with just the type comparison changes as that's where most of the performance was gained.

**Pull request closed without merging**
