### PR TITLE
Code refactor

### PR DESCRIPTION
**Pull request by torbacz**
## Description

- Reduced code nesting by inverting if statements.
- Extracted same code into one method
- Removed redundant else statements
- Removed unused code (only private/internals)

## How Has This Been Tested?
Unit tests

## Types of changes

- [x] Improvement (non-breaking change that improves a feature, code or algorithm)
- [ ] Bug fix (non-breaking change which fixes an issue with code or algorithm)
- [ ] New feature (non-breaking change which adds functionality to code)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Config and build (change in the configuration and build system, has no impact on code or features)
- [ ] Dependencies (update dependencies and changes associated, has no impact on code or features)
- [ ] Unit Tests (add new Unit Test(s) or improved existing one(s), has no impact on code or features)
- [ ] Documentation (changes or updates in the documentation, has no impact on code or features)

## Checklist:

- [x] My code follows the code style of this project (only if there are changes in source code).
- [ ] My changes require an update to the documentation (there are changes that require the docs website to be updated).
- [x] I have updated the documentation accordingly (the changes require an update on the docs in this repo).
- [x] I have read the [CONTRIBUTING](https://github.com/nanoframework/.github/blob/master/CONTRIBUTING.md) document.
- [x] I have tested everything locally and all new and existing tests passed (only if there are changes in source code).
- [ ] I have added new tests to cover my changes.

### CODE REVIEW

**Comment by torbacz** [comment]
There are a lot of changes, but each one was introduced as one commit. So the best way to review is to go one commit by one.

PS. I know it would be better to create PR for each change, but then we would end up with ~20 PR and it would introduce a lot of conflicts during merges.

**Comment by josesimoes** [comment]
> PS. I know it would be better to create PR for each change, but then we would end up with ~20 PR and it would introduce a lot of conflicts during merges.

No worries. If this is a code refactor, it's OK to have it in a single PR. Sometimes these are big and that's OK. Blessed Unit Tests so we can take all these changes with confidence!! 😅

**Comment by josesimoes** [comment]
@torbacz as you're on refactor mood, can you please address the only "code smell" that Sonarcloud is pointing? This would bring the code one step closer to _perfection_. 😉

**Comment by torbacz** [comment]
@josesimoes 
Fixed sonar issue, but I think this code can be deleted (whole ExitSerialization and EnterSerialization methods). They are invoked from internal classes from public override ToString method which is not invoked anywhere in Json code. 

image
image

But let's leave that for another PR.

**Comment by josesimoes** [comment]
@torbacz can you please run the Unit Tests locally using a real device and share the comparison output here? Each test has (if not they should have it) an output reporting the execution time for the serialization/deserialization. 

As this PR envolves significant changes in the code, we need to make sure that the code performance is not harmed.

**Comment by torbacz** [comment]
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/Marcin/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/Marcin/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
</head>

<body link="#0563C1" vlink="#954F72">



  | New | Old | New-Old
-- | -- | -- | --
BasicDeserializationTest | 60 | 50 | 10
BasicSerializationTest | 20 | 30 | -10
Can_serialize_and_deserialize_arrays_of_class_objects | 490 | 510 | -20
  | 670 | 620 | 50
Can_serialize_and_deserialize_complex_object | 280 | 280 | 0
  | 440 | 500 | -60
Can_serialize_and_deserialize_double | 20 | 20 | 0
  | 20 | 20 | 0
Can_serialize_and_deserialize_float | 20 | 20 | 0
  | 30 | 20 | 10
Can_serialize_and_deserialize_nan_double | 20 | 10 | 10
  | 10 | 20 | -10
Can_serialize_and_deserialize_nan_float | 20 | 10 | 10
  | 10 | 20 | -10
Can_serialize_and_deserialize_simple_object | 30 | 30 | 0
  | 40 | 40 | 0
Can_serialize_deserialize_timespan_00 | 60 | 70 | -10
  | 110 | 100 | 10
Can_serialize_deserialize_timespan_01 | 60 | 70 | -10
  | 70 | 100 | -30
Can_serialize_deserialize_timespan_02 | 90 | 70 | 20
Can_serialize_deserialize_timestamp | 40 | 50 | -10
  | 40 | 30 | 10
Can_serialize_int_array | 20 | 10 | 10
  | 20 | 20 | 0
Can_serialize_short_array | 10 | 10 | 0
  | 30 | 30 | 0
CanDeserializeAzureTwinProperties_01 | 80 | 80 | 0
CanDeserializeAzureTwinProperties_02 | 510 | 470 | 40
CanDeserializeAzureTwinProperties_03 | 480 | 440 | 40
CanDeserializeAzureTwinProperties_04 | 490 | 450 | 40
CanDeserializeInvocationReceiveMessage_01 | 10 | 20 | -10
CanDeserializeInvocationReceiveMessage_02 | 90 | 100 | -10
CanDeserializeInvocationReceiveMessage_03 | 220 | 200 | 20
CanDeserializeInvocationReceiveMessage_04 | 220 | 200 | 20
CanDeserializeInvocationReceiveMessage_05 | 60 | 60 | 0
CanDeserializeUnicodeData_01 | 60 | 60 | 0
CompleHashtableArraysList | 220 | 210 | 10
DeserializeArrayList | 90 | 80 | 10
DeserializeArrayListElements | 70 | 70 | 0
DeserializeArrayToDeserialize | 80 | 80 | 0
  | 100 | 90 | 10
DeserializeSingleTypesClassDeserialization | 170 | 150 | 20
SerializeAbstractClassTest | 30 | 30 | 0
SerializeArrayListInAnObject | 50 | 40 | 10
SerializeDeserializeDateTest | 10 | 20 | -10
SerializeObjectAsAProperty | 30 | 30 | 0
SerializeSimpleClassTest | 170 | 170 | 0



</body>

</html>


Value with "-" means new one is slower.

This one may be more readable :)

image

Ran on ESP32 DevKit

System Information
HAL build info: nanoCLR running @ ESP32 built with ESP-IDF v4.4.1
  Target:   ESP32
  Platform: ESP32

Firmware build Info:
  Date:        Jun 29 2022
  Type:        MinSizeRel build, chip rev. >= 0, without support for PSRAM
  CLR Version: 1.8.0.383
  Compiler:    GNU ARM GCC v8.4.0

**Comment by torbacz** [comment]
@josesimoes 
I've included only the tests that are reporting times (few of them are not). 

In my opinion changes doesn't affect performance at all. The differences are too small. But it's up to you.

**Comment by josesimoes** [comment]
@torbacz thanks for taking the time to sumarize these in a such professional fashion! 💯 
I agree that the time differences (for worst) are neglegtable and that, globally considered from a performance perspective, these changes are OK.

**Review by josesimoes — APPROVED** [review]
LGTM!

**Pull request merged**
