### PR TITLE
Rename Settings to JsonSettings

### PR DESCRIPTION
**Pull request by CoryCharlton**
## Description
- Create new `JsonSettings` class that mirrors existing `Settings` class.
- Update `Settings` to delegate properties to `JsonSettings`
- Mark `Settings` as obsolete

## Motivation and Context
This is an opinionated change and entirely optional. My strong belief is that code should be self documenting and the existing `Settings` class, without the namespace context, is ambiguous. 

By renaming to `JsonSettings` the intent is clear and users (like me) that don't read the documentation are more likely to discover the class.

- nanoFramework/Home#1382

## How Has This Been Tested?
- Unit tests
- Live device

## Types of changes

- [X] Improvement (non-breaking change that improves a feature, code or algorithm)
- [ ] Bug fix (non-breaking change which fixes an issue with code or algorithm)
- [X] New feature (non-breaking change which adds functionality to code)
- [x] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Config and build (change in the configuration and build system, has no impact on code or features)
- [ ] Dependencies (update dependencies and changes associated, has no impact on code or features)
- [x] Unit Tests (add new Unit Test(s) or improved existing one(s), has no impact on code or features)
- [ ] Documentation (changes or updates in the documentation, has no impact on code or features)

## Checklist:
- [X] My code follows the code style of this project (only if there are changes in source code).
- [X] My changes require an update to the documentation (there are changes that require the docs website to be updated).
- [ ] I have updated the documentation accordingly (the changes require an update on the docs in this repo).
- [ ] I have read the [CONTRIBUTING](https://github.com/nanoframework/.github/blob/main/CONTRIBUTING.md) document.
- [ ] I have tested everything locally and all new and existing tests passed (only if there are changes in source code).
- [x] I have added new tests to cover my changes.

### CODE REVIEW

**Comment by CoryCharlton** [comment]
@josesimoes I heard that you ❤️ PRs ;)

**Review by Ellerbach — APPROVED** [review]
Yes, we do ❤️ PR :-) And also additional tests. Thanks for this one. It looks good all up for me!

**Comment by josesimoes** [comment]
Well... if we're going to touch this anyways, let's follow our principle and try to mirror .NET official API as much as possible.
For consistency, a name like this should be _Options_ instead of _Settings_.

There's already a similar property: https://learn.microsoft.com/en-us/dotnet/api/system.text.json.jsonserializeroptions.propertynamecaseinsensitive?view=net-7.0 in class that's pretty much this.

So, following the .NET pattern, I suggest this design:

- Class should be named `JsonSerializerOptions`
- Shouldn't be static, instead have a constructor that sets the default values.
- (not entirely necessary, bute nice to have) Have a static property `[JsonSerializerDefaults](https://learn.microsoft.com/en-us/dotnet/api/system.text.json.jsonserializerdefaults?view=net-7.0)`.
- `SerializeObject` and `DeserializeObject` should have an overloaded constructor that accepts a `JsonSerializerOptions` parameter. This, in particular, addresses the discoverability issue pointed by @CoryCharlton. A developer looks at the method and can immediately notice that there are options that can be set, instead of having those options coming from a static class that is "hidden".

**Comment by josesimoes** [comment]
Well... if we're going to touch this anyways, let's follow our principle and try to mirror .NET official API as much as possible.
For consistency, a name like this should be _Options_ instead of _Settings_.

There's already a similar property: https://learn.microsoft.com/en-us/dotnet/api/system.text.json.jsonserializeroptions.propertynamecaseinsensitive?view=net-7.0 in class that's pretty much this.

So, following the .NET pattern, I suggest this design:

- Class should be named `JsonSerializerOptions`
- Shouldn't be static, instead have a constructor that sets the default values.
- (not entirely necessary, still) Have a static property `[JsonSerializerDefaults](https://learn.microsoft.com/en-us/dotnet/api/system.text.json.jsonserializerdefaults?view=net-7.0)`.
- `SerializeObject` and `DeserializeObject` should have an overloaded constructor that accepts a `JsonSerializerOptions` parameter. This in particular, addresses the discoverability issue pointed by @CoryCharlton. A developer looks at the method and can imediatly notice that there are options that can be set, instead of having them 

If a more "lightweight" approach it preferred, then let's have a `JsonSerializerOptions` property in

**Comment by torbacz** [comment]
I agree with Jose, we should stick to full .net naming whenever we can. Also creating default constructor and second one with options as parameters seems like good idea.

**Comment by CoryCharlton** [comment]
Sounds good. I wasn't sure how the project handled breaking changes so I avoided that. Happy to look into bringing this more in line with the .NET official API.

**Comment by Ellerbach** [comment]
>  I wasn't sure how the project handled breaking changes so I avoided that
When it's possible, we avoid. In that case, if the change is much better and fully align with the new .NET Json API, then let's go. Still, from my perspective, you can keep the original option with an obsolete mark as you've started. This Json lib is quite used!

**Comment by networkfusion** [comment]
Noting that this PR is getting on a bit... is there anything that needs updating / blockers?

**Comment by CoryCharlton** [comment]
> Noting that this PR is getting on a bit... is there anything that needs updating / blockers?

The suggestions in this comment still need to be looked into: https://github.com/nanoframework/nanoFramework.Json/pull/312#issuecomment-1757280413

This PR just got lost in the fold. I'll take a look at it.

**Comment by CoryCharlton** [comment]
So I might have gone a little overboard ;)

While I was digging through `JsonConvert` I saw a bunch of duplicate code and room for improvement. There's still a few ideas I have for further improvement but I'll hold off on those. Long story short most of the deserialization benchmarks saw a ~25% improvement.

**Comment by josesimoes** [comment]
@CoryCharlton these look great! In particular those improvements in deserialization.
You know what I'll write next: we prefer atomic PRs. 😁 
Can you please split this in two PRs? Not sure if it's easier to rename this to rework........ and extract the JsonSetting rename to another or keep that here and extract the rework. You decide. 😉

**Comment by CoryCharlton** [comment]
Apparently renaming the branch involves deleting the old one behind the scenes... 

I'll open new PRs for both changes.

**Pull request closed without merging**
