### PR TITLE
Allow deserialization when properties case doesn't match

### PR DESCRIPTION
**Pull request by torbacz**
## Description

- Rework setting values - replaced with IMemberResolver
- Two implementation for IMemberResolver - CaseSensitive (old one, default), CaseInsensitive
- Implemented few more converters and fixed others
- Created new static class "Settings" for easier managing JSON serialization. Currently, Only switch for CaseSensitive
- New unit tests to cover new areas

NOTE: Benchmarks without IntArray and ShortArray due to possible bug.
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/Marcin/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/Marcin/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">

</head>

<body link="#0563C1" vlink="#954F72">

Benchmark name | Method   name | Current   master | New | New vs   Master
-- | -- | -- | -- | --
ReferenceTypesSerializationBenchmark | IntArray | 146 | 140 | -6
  | ShortArray | 142 | 134 | -8
  | String | 64 | 62 | -2
  | NestedClass | 160 | 146 | -14
  | ComplexObject | 252 | 230 | -22
  | ComplexArrayObject | 440 | 412 | -28
  | ArrayList | 460 | 412 | -48
ReferenceTypesDeserializationBenchmark | IntArray | 732 | 0 | -732
  | ArrayList | 1192 | 1160 | -32
  | ComplexObjectAzureTwinPayload | 572 | 584 | 12
  | ShortArray | 602 | 0 | -602
  | String | 180 | 156 | -24
  | NestedClass | 196 | 242 | 46
  | ComplexArrayObject | 734 | 890 | 156
ValueTypesDeserializationBenchmark | Short | 208 | 210 | 2
  | TimeSpanT | 348 | 350 | 2
  | Float | 224 | 224 | 0
  | Double | 238 | 234 | -4
  | DateTimeT | 304 | 310 | 6
  | Long | 238 | 236 | -2
  | EnumBoxed | 318 | 318 | 0
ValueTypesSerializationBenchmark | Short | 124 | 130 | 6
  | TimeSpanT | 138 | 148 | 10
  | Float | 176 | 174 | -2
  | Double | 164 | 168 | 4
  | DateTimeT | 1562 | 1300 | -262
  | Long | 130 | 136 | 6
  | Enum | 150 | 158 | 8
  | EnumBoxed | 650 | 590 | -60

</body>

</html>

## Motivation and Context

- Resolves nanoFramework/Home#1115

## Types of changes

- [x] Improvement (non-breaking change that improves a feature, code or algorithm)
- [x] Bug fix (non-breaking change which fixes an issue with code or algorithm)
- [x] New feature (non-breaking change which adds functionality to code)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Config and build (change in the configuration and build system, has no impact on code or features)
- [ ] Dependencies (update dependencies and changes associated, has no impact on code or features)
- [x] Unit Tests (add new Unit Test(s) or improved existing one(s), has no impact on code or features)
- [ ] Documentation (changes or updates in the documentation, has no impact on code or features)

## Checklist:

- [x] My code follows the code style of this project (only if there are changes in source code).
- [x] My changes require an update to the documentation (there are changes that require the docs website to be updated).
- [x] I have updated the documentation accordingly (the changes require an update on the docs in this repo).
- [x] I have read the [CONTRIBUTING](https://github.com/nanoframework/.github/blob/master/CONTRIBUTING.md) document.
- [x] I have tested everything locally and all new and existing tests passed (only if there are changes in source code).
- [x] I have added new tests to cover my changes.

### CODE REVIEW

**Comment by torbacz** [comment]
Left to do:
- Tests for resolvers
- Benchmarks for resolvers (CaseSensitive vs CaseInsensitive)

**Comment by torbacz** [comment]
Each benchmark was 2500 times resolving the same property, each test class contained 5 fields/properties and the last one was the one which was resolved.
```csharp
[IterationCount(10)]
public class ResolverFieldBenchmark
{
    private class ClassWithField
    {
        public string TestField1;
        public string TestField2;
        public string TestField3;
        public string TestField4;
        public string TestField5;
    }

    private CaseSensitiveResolver caseSensitiveResolver;
    private CaseInsensitiveResolver caseInsensitiveResolver;
    private Type typeToCheck;
    private const short ResolvingCount = 2500;

    [Setup]
    public void SetUp()
    {
        caseSensitiveResolver = new CaseSensitiveResolver();
        caseInsensitiveResolver = new CaseInsensitiveResolver();
        typeToCheck = typeof(ClassWithField);
    }

    [Benchmark]
    [Baseline]
    public void CaseSensitive_FieldResolve()
    {
        for (int i = 0; i < ResolvingCount; i++)
        {
            var field = caseSensitiveResolver.GetResolver(nameof(ClassWithField.TestField5), typeToCheck);
        }
    }

    [Benchmark]
    public void CaseInsensitive_FieldResolve()
    {
        for (int i = 0; i < ResolvingCount; i++)
        {
            var field = caseInsensitiveResolver.GetResolver(nameof(ClassWithField.TestField5), typeToCheck);
        }
    }
}

[IterationCount(10)]
public class ResolverPropertyBenchmark
{
    private class ClassWithProperty
    {
        public string TestField1 { get; set; }
        public string TestField2 { get; set; }
        public string TestField3 { get; set; }
        public string TestField4 { get; set; }
        public string TestField5 { get; set; }
    }

    private CaseSensitiveResolver caseSensitiveResolver;
    private CaseInsensitiveResolver caseInsensitiveResolver;
    private Type typeToCheck;
    private const short ResolvingCount = 2500;

    [Setup]
    public void SetUp()
    {
        caseSensitiveResolver = new CaseSensitiveResolver();
        caseInsensitiveResolver = new CaseInsensitiveResolver();
        typeToCheck = typeof(ClassWithProperty);
    }

    [Benchmark]
    [Baseline]
    public void CaseSensitive_PropertyResolve()
    {
        for (int i = 0; i < ResolvingCount; i++)
        {
            var field = caseSensitiveResolver.GetResolver(nameof(ClassWithProperty.TestField5), typeToCheck);
        }
    }

    [Benchmark]
    public void CaseInensitive_PropertyResolve()
    {
        for (int i = 0; i < ResolvingCount; i++)
        {
            var field = caseInsensitiveResolver.GetResolver(nameof(ClassWithProperty.TestField5), typeToCheck);
        }
    }
}
```

```text
Console export: ResolverPropertyBenchmark benchmark class.
| MethodName                     | ItterationCount | Mean     | Ratio  | Min       | Max       |
| -------------------------------------------------------------------------------------------- |
| CaseSensitive_PropertyResolve  | 10              | 2891 ms  | 1.0    | 2,860 ms  | 2,920 ms  |
| CaseInensitive_PropertyResolve | 10              | 16589 ms | 5.7381 | 16,550 ms | 16,630 ms |


Console export: ResolverFieldBenchmark benchmark class.
| MethodName                   | ItterationCount | Mean    | Ratio  | Min      | Max      |
| --------------------------------------------------------------------------------------- |
| CaseSensitive_FieldResolve   | 10              | 1911 ms | 1.0    | 1,880 ms | 1,950 ms |
| CaseInsensitive_FieldResolve | 10              | 5825 ms | 3.0481 | 5,780 ms | 5,860 ms |
```

Like i thought, current implementation for insensitive members resolving is much slower. It's none default one, so it has no impact on standard mode.

**Comment by torbacz** [comment]
It would mean:
- Double iterate in worst case scenario
- We need to track/remove already handled objects - memory impact when tracking or performance when removing. Also we don't want to remove objects from collection we are iterating through. It may lead to very nasty bugs.
- Then we need to call the same code, but with case insensitive resolver
I'm a little bit worried about about performance and memory usage.

I would rather go with similar approach as current, but instead of having two "Resolvers" just merge them into one. In short, if the "case sensitive" can't find member, then call "case insensitive". If "case insensitive" can't find member - then throw exception.  It would also mean removing few lines of code and classes. 
Any thoughts?

**Comment by josesimoes** [comment]
I'm not seeing an easy alternative to tackle this. Any of the approaches that are possible with what we have available will incurr in a performance penalty.

Questions:
1. Do we really need to add support for case insensitive deserialization? I mean, this is nano, we make compromises every day and with most APIs. This is one of those.
2. Can look into adding support for case insensitive in the CLR. Then we would just have to add the case sensitive property to configure this, like with the full framework. Is it worth it? This hasn't been implemented since NETMF time. Probably for a good reason.

**Comment by Ellerbach** [comment]
> 2\. Can look into adding support for case insensitive in the CLR. Then we would just have to add the case sensitive property to configure this, like with the full framework. Is it worth it? This hasn't been implemented since NETMF time. Probably for a good reason.

Yes, we can definitely add an option for that. That will allow to add options for other scenarios like in the larger framework. And we then should be very very very clear on the performance impact. Still if we add the option, I do think we should try to minimize the perf impact. But 100% agree, there will be one!

**Comment by torbacz** [comment]
@josesimoes 
Well, in only nano we can work with case sensitive deserialization. But the problem is when we start integrating nano devices with .NET API which by default serialize into JSON with lowercase first letter in json property name. So the property "TestProperty" becomes "testProperty". Of course we can change configuration for .NET API, but it would require to change it in every new API. The use case for such mechanism is when we want to configure nano device from .NET application (colleague of mine implemented such UI with Blazor and nanoFramework. Announcement, soon 😄)

One more proposition from me. 
https://github.com/nanoframework/nanoFramework.Json/blob/9ff4e29e4b9dbec7903618d3e0b64434c1f1925e/nanoFramework.Json/Resolvers/CaseSensitiveResolver.cs

If we can't find property with match case, we are calling case insensitive methods. If case insensitive fails, then throw exception.

**Comment by josesimoes** [comment]
I'll look into adding support for case sensitive comparison in mscorlib. Just can't promise it for tomorrow...

**Comment by Ellerbach** [comment]
> I've just pushed new files. Please check the tests for resolver, they describe all resolver logic.
> https://github.com/torbacz/nanoFramework.Json/tree/cleanup/nanoFramework.Json.Test/Resolvers

Thanks. I have to say I like the logic. And for the settings, the throw if member does not exist should be false by default here https://github.com/torbacz/nanoFramework.Json/blob/cc521313b5869e784916ed4d3a827d69a6e37598/nanoFramework.Json/Configuration/Settings.cs#L18

So this will still involve a little bit of performance issue compare to the "past" use case where we had nothing at all. But with the recent improvements, we can for sure lose a little bit to be able to get this very nice addition.

What I also like is the possibility to have your own resolver. That can be very handy to map some enums or strings or whatever.

**Comment by torbacz** [comment]
New benchmark results
image

Legend:
- Green -> better
- Red -> worse
- Yellow -> no change/no benchmark on new code

I'm a little bit worried about about deserialization for "NestedClasss" and "ComplexArrayObject". I want to investigate it before merging.

**Comment by josesimoes** [comment]
@torbacz this is looking good! I share your worries. Those are heavily used cases for json payloads...

**Comment by torbacz** [comment]
@josesimoes I found it, the "problem" is in StringConverter, when I've changed it to "just return input object" the performance was pretty much the same.
image

But it needs to go through all the logic to escape all required characters in string object. 

In my option we should:
1. Create several issues based on findings:
- Improve performance of StringConverter.ToType
- Remove JsonValue DateTime conversion and change logic in DateTime converter (currently it's returning input object without conversion)
- Try to remove conversion from private static JsonToken ParseValue(ref LexToken token) method (should be handled by converters)
- Maybe something else?
2. Merge this PR 

Then someone (probably I'll take it) can work on further cleanup/performance in JSON.

**Comment by josesimoes** [comment]
@torbacz nice finding!! 👏🏻  persistence pays off!! 😉 

There's a [project](https://github.com/orgs/nanoframework/projects/30) for the json library.

Please add any tasks and to-do's there. We can move those to issues in order to track progress as needed.
We shouldn't clutter the issue list with todo's and planned stuff, otherwise is becomes messy and hard to read, specially from outsiders looking at the project. 

I would suggest that we discuss this on Discord. It's a more suitable and streamlined experience. (we can add the URL for the thread here for reference)

**Comment by torbacz** [comment]
@josesimoes 
Finally, I've got some time to finish this one. 
I've added tasks in the [project](https://github.com/orgs/nanoframework/projects/30) page.  We can discus them later on discord.

Are we ready to merge this one?

**Review by josesimoes — APPROVED** [review]
LGTM!

**Comment by josesimoes** [comment]
@torbacz I'm good with these changes. OK for discussing on Discord. 👍🏻 

@Ellerbach any other take on this?

**Pull request merged**
