### PR TITLE
Attempt to handle doubles correctly.

### PR DESCRIPTION
**Pull request by networkfusion**
## Description
Add double tests

## Motivation and Context
doubles were not supported correctly after recent changes involving the math lib.
This is an attempt at resolving it (in the mid term)

## How Has This Been Tested?
WiP

## Types of changes

- [x] Improvement (non-breaking change that improves a feature, code or algorithm)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Config and build (change in the configuration and build system, has no impact on code or features)
- [ ] Dependencies (update dependencies and changes associated, has no impact on code or features)
- [ ] Unit Tests (work on Unit Tests, has no impact on code or features)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [CONTRIBUTING](https://github.com/nanoframework/.github/blob/master/CONTRIBUTING.md) document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by josesimoes** [comment]
@networkfusion can you please take care of these conflicts?

**Comment by networkfusion** [comment]
@josesimoes Will do, but TBH I never got it the attempt to work properly, so might need to wait until we have something better 😉

**Comment by josesimoes** [comment]
Please don't forget to address the merge conflict. That's what blocking the build right now.

**Comment by networkfusion** [comment]
Will do... but would like to get the tests passing first... then I can rebase...

**Comment by networkfusion** [comment]
@josesimoes BTW, the conflict with `nanoFramework.Json/packages.config` seems stuck for me... If I click on the `web editor` or `resolve conflicts` link, it just returns to this PR!

**Comment by networkfusion** [comment]
All tests now pass locally (with notes).

**Comment by networkfusion** [comment]
All tests pass locally for me:
image

**Review by josesimoes — APPROVED** [review]
LGTM! 👍🙂

**Pull request merged**
